///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VBS_Android
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Manage_Click recording.
    /// </summary>
    [TestModule("15d642ae-ad7f-4384-8931-d7443d69fd30", ModuleType.Recording, 1)]
    public partial class Manage_Click : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VBS_AndroidRepository repository.
        /// </summary>
        public static VBS_AndroidRepository repo = VBS_AndroidRepository.Instance;

        static Manage_Click instance = new Manage_Click();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Manage_Click()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Manage_Click Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Touch", "Touch item 'ComVodafoneViewer.LoginActivity._Manage_Click' at Center", repo.ComVodafoneViewer.LoginActivity._Manage_ClickInfo, new RecordItemIndex(0));
            repo.ComVodafoneViewer.LoginActivity._Manage_Click.Touch();
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
