///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace VBS_Android
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Username_Enter recording.
    /// </summary>
    [TestModule("a5a4fe9a-b9fb-479f-aa38-d3b4b0ba362a", ModuleType.Recording, 1)]
    public partial class Username_Enter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the VBS_AndroidRepository repository.
        /// </summary>
        public static VBS_AndroidRepository repo = VBS_AndroidRepository.Instance;

        static Username_Enter instance = new Username_Enter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Username_Enter()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Username_Enter Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Text to 'Ramya' on item 'ComVodafoneViewer.Content.Ramya'.", repo.ComVodafoneViewer.Content.RamyaInfo, new RecordItemIndex(0));
            repo.ComVodafoneViewer.Content.Ramya.Element.SetAttributeValue("Text", "Ramya");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
