///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace VBS_Android
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the VBS_AndroidRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("33ac3cb3-8a0e-4e95-9bfa-a7bed713ab3b")]
    public partial class VBS_AndroidRepository : RepoGenBaseFolder
    {
        static VBS_AndroidRepository instance = new VBS_AndroidRepository();
        VBS_AndroidRepositoryFolders.ComVodafoneViewerAppFolder _comvodafoneviewer;

        /// <summary>
        /// Gets the singleton class instance representing the VBS_AndroidRepository element repository.
        /// </summary>
        [RepositoryFolder("33ac3cb3-8a0e-4e95-9bfa-a7bed713ab3b")]
        public static VBS_AndroidRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public VBS_AndroidRepository() 
            : base("VBS_AndroidRepository", "/", null, 0, false, "33ac3cb3-8a0e-4e95-9bfa-a7bed713ab3b", ".\\RepositoryImages\\VBS_AndroidRepository33ac3cb3.rximgres")
        {
            _comvodafoneviewer = new VBS_AndroidRepositoryFolders.ComVodafoneViewerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("33ac3cb3-8a0e-4e95-9bfa-a7bed713ab3b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The ComVodafoneViewer folder.
        /// </summary>
        [RepositoryFolder("9acfde88-7e51-4186-977d-bd5630653872")]
        public virtual VBS_AndroidRepositoryFolders.ComVodafoneViewerAppFolder ComVodafoneViewer
        {
            get { return _comvodafoneviewer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class VBS_AndroidRepositoryFolders
    {
        /// <summary>
        /// The ComVodafoneViewerAppFolder folder.
        /// </summary>
        [RepositoryFolder("9acfde88-7e51-4186-977d-bd5630653872")]
        public partial class ComVodafoneViewerAppFolder : RepoGenBaseFolder
        {
            VBS_AndroidRepositoryFolders.ContentFolder _content;
            VBS_AndroidRepositoryFolders.LoginActivityFolder _loginactivity;
            VBS_AndroidRepositoryFolders.RelativeFolder _relative;
            VBS_AndroidRepositoryFolders.FormNoneFolder _formnone;
            RepoItemInfo _pw2Info;
            RepoItemInfo _connect2Info;

            /// <summary>
            /// Creates a new ComVodafoneViewer  folder.
            /// </summary>
            public ComVodafoneViewerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ComVodafoneViewer", "/mobileapp[@title='com.vodafone.viewer']", parentFolder, 30000, null, false, "9acfde88-7e51-4186-977d-bd5630653872", "")
            {
                _content = new VBS_AndroidRepositoryFolders.ContentFolder(this);
                _loginactivity = new VBS_AndroidRepositoryFolders.LoginActivityFolder(this);
                _relative = new VBS_AndroidRepositoryFolders.RelativeFolder(this);
                _formnone = new VBS_AndroidRepositoryFolders.FormNoneFolder(this);
                _pw2Info = new RepoItemInfo(this, "PW2", "form[@title='Enter the password']/container[@rid='content']/androidelement/container[3]/container[@rid='custom']/androidelement/androidelement[2]/container[@containertype='Frame']/text", 30000, null, "1e343614-d4a4-4e2f-ba64-941c0df33801");
                _connect2Info = new RepoItemInfo(this, "Connect2", "form[@title='Enter the password']/container[@rid='content']//button[@rid='button1']", 30000, null, "ab6b2e51-3de7-472b-85ff-f8f069b5be04");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9acfde88-7e51-4186-977d-bd5630653872")]
            public virtual Ranorex.MobileApp Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MobileApp>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9acfde88-7e51-4186-977d-bd5630653872")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The PW2 item.
            /// </summary>
            [RepositoryItem("1e343614-d4a4-4e2f-ba64-941c0df33801")]
            public virtual Ranorex.Text PW2
            {
                get
                {
                    return _pw2Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The PW2 item info.
            /// </summary>
            [RepositoryItemInfo("1e343614-d4a4-4e2f-ba64-941c0df33801")]
            public virtual RepoItemInfo PW2Info
            {
                get
                {
                    return _pw2Info;
                }
            }

            /// <summary>
            /// The Connect2 item.
            /// </summary>
            [RepositoryItem("ab6b2e51-3de7-472b-85ff-f8f069b5be04")]
            public virtual Ranorex.Button Connect2
            {
                get
                {
                    return _connect2Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Connect2 item info.
            /// </summary>
            [RepositoryItemInfo("ab6b2e51-3de7-472b-85ff-f8f069b5be04")]
            public virtual RepoItemInfo Connect2Info
            {
                get
                {
                    return _connect2Info;
                }
            }

            /// <summary>
            /// The Content folder.
            /// </summary>
            [RepositoryFolder("79dc68bb-9e6d-4778-9e7c-a0fabc004998")]
            public virtual VBS_AndroidRepositoryFolders.ContentFolder Content
            {
                get { return _content; }
            }

            /// <summary>
            /// The LoginActivity folder.
            /// </summary>
            [RepositoryFolder("84b52ec2-9b23-4351-8b0c-f3106c4f56cb")]
            public virtual VBS_AndroidRepositoryFolders.LoginActivityFolder LoginActivity
            {
                get { return _loginactivity; }
            }

            /// <summary>
            /// The Relative folder.
            /// </summary>
            [RepositoryFolder("abf44cd1-33ab-41da-b4d4-a139c08aa95a")]
            public virtual VBS_AndroidRepositoryFolders.RelativeFolder Relative
            {
                get { return _relative; }
            }

            /// <summary>
            /// The FormNone folder.
            /// </summary>
            [RepositoryFolder("8d3307d8-b580-4c08-b642-6a5acf78d9fa")]
            public virtual VBS_AndroidRepositoryFolders.FormNoneFolder FormNone
            {
                get { return _formnone; }
            }
        }

        /// <summary>
        /// The ContentFolder folder.
        /// </summary>
        [RepositoryFolder("79dc68bb-9e6d-4778-9e7c-a0fabc004998")]
        public partial class ContentFolder : RepoGenBaseFolder
        {
            RepoItemInfo _nextInfo;
            RepoItemInfo _ramyaInfo;
            RepoItemInfo _passwordInfo;

            /// <summary>
            /// Creates a new Content  folder.
            /// </summary>
            public ContentFolder(RepoGenBaseFolder parentFolder) :
                    base("Content", "form[@title>'Enter the username and password']/container[@rid='content']", parentFolder, 30000, null, false, "79dc68bb-9e6d-4778-9e7c-a0fabc004998", "")
            {
                _nextInfo = new RepoItemInfo(this, "Next", ".//button[@rid='button1']", 30000, null, "46096f4d-b2c8-4289-9470-dc862bc03569");
                _ramyaInfo = new RepoItemInfo(this, "Ramya", "androidelement/container[3]/container[@rid='custom']//text", 30000, null, "42daaab2-ee04-48aa-99e8-dbf498dc7785");
                _passwordInfo = new RepoItemInfo(this, "Password", "androidelement/container[3]/container[@rid='custom']/androidelement/androidelement[2]/container[@containertype='Frame']/text", 30000, null, "fe6e7a54-db64-46a5-bf9d-52199fec0a98");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("79dc68bb-9e6d-4778-9e7c-a0fabc004998")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("79dc68bb-9e6d-4778-9e7c-a0fabc004998")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Next item.
            /// </summary>
            [RepositoryItem("46096f4d-b2c8-4289-9470-dc862bc03569")]
            public virtual Ranorex.Button Next
            {
                get
                {
                    return _nextInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Next item info.
            /// </summary>
            [RepositoryItemInfo("46096f4d-b2c8-4289-9470-dc862bc03569")]
            public virtual RepoItemInfo NextInfo
            {
                get
                {
                    return _nextInfo;
                }
            }

            /// <summary>
            /// The Ramya item.
            /// </summary>
            [RepositoryItem("42daaab2-ee04-48aa-99e8-dbf498dc7785")]
            public virtual Ranorex.Text Ramya
            {
                get
                {
                    return _ramyaInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Ramya item info.
            /// </summary>
            [RepositoryItemInfo("42daaab2-ee04-48aa-99e8-dbf498dc7785")]
            public virtual RepoItemInfo RamyaInfo
            {
                get
                {
                    return _ramyaInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("fe6e7a54-db64-46a5-bf9d-52199fec0a98")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("fe6e7a54-db64-46a5-bf9d-52199fec0a98")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }
        }

        /// <summary>
        /// The LoginActivityFolder folder.
        /// </summary>
        [RepositoryFolder("84b52ec2-9b23-4351-8b0c-f3106c4f56cb")]
        public partial class LoginActivityFolder : RepoGenBaseFolder
        {
            RepoItemInfo __manage_clickInfo;
            RepoItemInfo _connectInfo;
            RepoItemInfo _edit_clickInfo;

            /// <summary>
            /// Creates a new LoginActivity  folder.
            /// </summary>
            public LoginActivityFolder(RepoGenBaseFolder parentFolder) :
                    base("LoginActivity", "form[@title='LoginActivity']", parentFolder, 30000, null, false, "84b52ec2-9b23-4351-8b0c-f3106c4f56cb", "")
            {
                __manage_clickInfo = new RepoItemInfo(this, "_Manage_Click", ".//container[@containertype='Linear']/?/?/button[@text='manage']", 30000, null, "7fc6d8c4-6de3-4e2a-97b4-8890e1881950");
                _connectInfo = new RepoItemInfo(this, "Connect", "androidelement[@rid='content']//container[@containertype='Frame']/androidelement/container[@containertype='Relative']/container[@containertype='Relative']/button[@text='Connect']", 30000, null, "1ef55bcd-da1e-4fa1-9aa7-be0eedc88c50");
                _edit_clickInfo = new RepoItemInfo(this, "Edit_Click", "androidelement[@rid='content']//container[@containertype='Frame']/androidelement/container[@containertype='Relative']/container[@containertype='Relative']/button[@text='Edit']", 30000, null, "ecf455c8-0859-48f2-8a9d-b927a11864b3");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("84b52ec2-9b23-4351-8b0c-f3106c4f56cb")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("84b52ec2-9b23-4351-8b0c-f3106c4f56cb")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The _Manage_Click item.
            /// </summary>
            [RepositoryItem("7fc6d8c4-6de3-4e2a-97b4-8890e1881950")]
            public virtual Ranorex.Button _Manage_Click
            {
                get
                {
                    return __manage_clickInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The _Manage_Click item info.
            /// </summary>
            [RepositoryItemInfo("7fc6d8c4-6de3-4e2a-97b4-8890e1881950")]
            public virtual RepoItemInfo _Manage_ClickInfo
            {
                get
                {
                    return __manage_clickInfo;
                }
            }

            /// <summary>
            /// The Connect item.
            /// </summary>
            [RepositoryItem("1ef55bcd-da1e-4fa1-9aa7-be0eedc88c50")]
            public virtual Ranorex.Button Connect
            {
                get
                {
                    return _connectInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Connect item info.
            /// </summary>
            [RepositoryItemInfo("1ef55bcd-da1e-4fa1-9aa7-be0eedc88c50")]
            public virtual RepoItemInfo ConnectInfo
            {
                get
                {
                    return _connectInfo;
                }
            }

            /// <summary>
            /// The Edit_Click item.
            /// </summary>
            [RepositoryItem("ecf455c8-0859-48f2-8a9d-b927a11864b3")]
            public virtual Ranorex.Button Edit_Click
            {
                get
                {
                    return _edit_clickInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Edit_Click item info.
            /// </summary>
            [RepositoryItemInfo("ecf455c8-0859-48f2-8a9d-b927a11864b3")]
            public virtual RepoItemInfo Edit_ClickInfo
            {
                get
                {
                    return _edit_clickInfo;
                }
            }
        }

        /// <summary>
        /// The RelativeFolder folder.
        /// </summary>
        [RepositoryFolder("abf44cd1-33ab-41da-b4d4-a139c08aa95a")]
        public partial class RelativeFolder : RepoGenBaseFolder
        {
            RepoItemInfo _alertsInfo;
            RepoItemInfo _mapsInfo;
            RepoItemInfo _viewoptionsInfo;

            /// <summary>
            /// Creates a new Relative  folder.
            /// </summary>
            public RelativeFolder(RepoGenBaseFolder parentFolder) :
                    base("Relative", "form[@title='HomeScreenActivity']/androidelement[@rid='content']/androidelement/androidelement[1]/androidelement[1]/androidelement[1]/container[@containertype='Relative']", parentFolder, 30000, null, false, "abf44cd1-33ab-41da-b4d4-a139c08aa95a", "")
            {
                _alertsInfo = new RepoItemInfo(this, "Alerts", "androidelement[2]/container[@containertype='Frame']", 30000, null, "e7bff43f-ba7a-4189-8550-d6e7ed41b747");
                _mapsInfo = new RepoItemInfo(this, "Maps", "container[2]", 30000, null, "3feb973a-4bba-4b9f-8f3c-5518a0e064bf");
                _viewoptionsInfo = new RepoItemInfo(this, "ViewOptions", "picture", 30000, null, "f36a9a46-cc27-489b-9d9c-1c3aa89fe2a8");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("abf44cd1-33ab-41da-b4d4-a139c08aa95a")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("abf44cd1-33ab-41da-b4d4-a139c08aa95a")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Alerts item.
            /// </summary>
            [RepositoryItem("e7bff43f-ba7a-4189-8550-d6e7ed41b747")]
            public virtual Ranorex.Container Alerts
            {
                get
                {
                    return _alertsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Alerts item info.
            /// </summary>
            [RepositoryItemInfo("e7bff43f-ba7a-4189-8550-d6e7ed41b747")]
            public virtual RepoItemInfo AlertsInfo
            {
                get
                {
                    return _alertsInfo;
                }
            }

            /// <summary>
            /// The Maps item.
            /// </summary>
            [RepositoryItem("3feb973a-4bba-4b9f-8f3c-5518a0e064bf")]
            public virtual Ranorex.Container Maps
            {
                get
                {
                    return _mapsInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Maps item info.
            /// </summary>
            [RepositoryItemInfo("3feb973a-4bba-4b9f-8f3c-5518a0e064bf")]
            public virtual RepoItemInfo MapsInfo
            {
                get
                {
                    return _mapsInfo;
                }
            }

            /// <summary>
            /// The ViewOptions item.
            /// </summary>
            [RepositoryItem("f36a9a46-cc27-489b-9d9c-1c3aa89fe2a8")]
            public virtual Ranorex.Picture ViewOptions
            {
                get
                {
                    return _viewoptionsInfo.CreateAdapter<Ranorex.Picture>(true);
                }
            }

            /// <summary>
            /// The ViewOptions item info.
            /// </summary>
            [RepositoryItemInfo("f36a9a46-cc27-489b-9d9c-1c3aa89fe2a8")]
            public virtual RepoItemInfo ViewOptionsInfo
            {
                get
                {
                    return _viewoptionsInfo;
                }
            }
        }

        /// <summary>
        /// The FormNoneFolder folder.
        /// </summary>
        [RepositoryFolder("8d3307d8-b580-4c08-b642-6a5acf78d9fa")]
        public partial class FormNoneFolder : RepoGenBaseFolder
        {
            RepoItemInfo _logoutInfo;
            RepoItemInfo _buttonokInfo;
            RepoItemInfo _isthefrontendapplicationfromvodafoInfo;

            /// <summary>
            /// Creates a new FormNone  folder.
            /// </summary>
            public FormNoneFolder(RepoGenBaseFolder parentFolder) :
                    base("FormNone", "form[@title='(none)']", parentFolder, 30000, null, false, "8d3307d8-b580-4c08-b642-6a5acf78d9fa", "")
            {
                _logoutInfo = new RepoItemInfo(this, "Logout", "androidelement/androidelement/androidelement[5]/container[@rid='content']", 30000, null, "a0819414-b57f-4c71-bc3a-c2508e0b3564");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "container[@rid='content']//button[@resourceid='R.string.yes']", 30000, null, "e8723d7e-a1be-4f08-94a8-9ed6c81d9721");
                _isthefrontendapplicationfromvodafoInfo = new RepoItemInfo(this, "IsTheFrontEndApplicationFromVodafo", "container[@rid='content']//dom[@containertype='WebView']/body/div/div//article/section/p[@innertext>'is the front end application']", 30000, null, "06c0a936-e817-47d7-a9f7-4b5263169a50");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("8d3307d8-b580-4c08-b642-6a5acf78d9fa")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("8d3307d8-b580-4c08-b642-6a5acf78d9fa")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Logout item.
            /// </summary>
            [RepositoryItem("a0819414-b57f-4c71-bc3a-c2508e0b3564")]
            public virtual Ranorex.Container Logout
            {
                get
                {
                    return _logoutInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Logout item info.
            /// </summary>
            [RepositoryItemInfo("a0819414-b57f-4c71-bc3a-c2508e0b3564")]
            public virtual RepoItemInfo LogoutInfo
            {
                get
                {
                    return _logoutInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("e8723d7e-a1be-4f08-94a8-9ed6c81d9721")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("e8723d7e-a1be-4f08-94a8-9ed6c81d9721")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }

            /// <summary>
            /// The IsTheFrontEndApplicationFromVodafo item.
            /// </summary>
            [RepositoryItem("06c0a936-e817-47d7-a9f7-4b5263169a50")]
            public virtual Ranorex.PTag IsTheFrontEndApplicationFromVodafo
            {
                get
                {
                    return _isthefrontendapplicationfromvodafoInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The IsTheFrontEndApplicationFromVodafo item info.
            /// </summary>
            [RepositoryItemInfo("06c0a936-e817-47d7-a9f7-4b5263169a50")]
            public virtual RepoItemInfo IsTheFrontEndApplicationFromVodafoInfo
            {
                get
                {
                    return _isthefrontendapplicationfromvodafoInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
